<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Curriculum;
use App\Models\SchoolLevel;
use App\Models\Course;

class CoursesSeeder extends Seeder
{
    public function run(): void
    {
        $data = [

            // ✅ CBC Curriculum
            'CBC' => [
                'Nursery' => [
                    'Language Activities',
                    'Mathematical Activities',
                    'Environmental Activities',
                    'Psychomotor',
                    'Creative Activities',
                    'Religious and Moral Activities',
                ],
                'Primary' => [
                    'English',
                    'Kiswahili',
                    'Mathematics',
                    'Religious Education (CRE)',
                    'Religious Education (IRE)',
                    'Religious Education (HRE)',
                    'Social Studies',
                    'Science & Technology',
                    'Agriculture & Nutrition',
                    'Creative Arts',
                    'Physical & Health Education',
                    'Indigenous Languages',
                    'Hygiene & Nutritional Activities',
                    'Digital Literacy',
                    'Kenya Sign Language',
                    'Braille',
                    'Pastoral Program Instruction (PPI)',
                ],
                'Secondary' => [
                    'English',
                    'Kiswahili or Kenyan Sign Language',
                    'Mathematics',
                    'Integrated Science',
                    'Health Education',
                    'Pre-Technical and Pre-Career Education',
                    'Social Studies',
                    'Religious Education',
                    'Business Studies',
                    'Agriculture',
                    'Life Skills',
                    'Sports and Physical Education',
                    'Visual Arts',
                    'Performing Arts',
                    'Home Science',
                    'Computer Science',
                    'Foreign Languages (German, French, Mandarin, or Arabic)',
                    'Kenyan Sign Language',
                    'Indigenous Languages',
                ],
                'Secondary' => [
                    'Arts and Sports Science',
                    'Social Sciences',
                    'STEM',
                    'Legal and Ethical issues in Arts',
                    'Communication Skills',
                    'Performing Arts',
                    'Music',
                    'Dance',
                    'Theatre and Elocution',
                    'Fine Art',
                    'Applied Art',
                    'Time Based Media',
                    'Crafts',
                    'Athletics',
                    'Indoor Games',
                    'Gymnastics',
                    'Water Sports',
                    'Boxing',
                    'Martial Arts',
                    'Outdoor Pursuits',
                    'Advanced Physical Education',
                    'History and Citizenship',
                    'Geography',
                    'Christian Religious Education',
                    'Islamic Religious Education',
                    'Hindu Religious Education',
                    'Business Studies',
                    'Mathematics',
                    'English Language',
                    'Literature in English',
                    'Lugha ya Kiswahili',
                    'Fasihi ya Kiswahili',
                    'Kenyan Sign Language',
                    'Indigenous Languages',
                    'Arabic',
                    'French',
                    'German',
                    'Mandarin',
                    'Pure sciences',
                    'Applied sciences',
                    'Technical and engineering',
                    'Career in Technology Studies',
                    'Community Service Learning',
                    'Physical Education',
                    'ICT',
                    'Physics',
                    'Chemistry',
                    'Biology',
                    'Agriculture',
                    'Computer Science',
                    'Foods and Nutrition',
                    'Home Management',
                    'Agricultural Technology',
                    'Geosciences Technology',
                    'Marine and Fisheries Technology',
                    'Aviation Technology',
                    'Wood Technology',
                    'Electrical Technology',
                    'Metal Technology',
                    'Power Mechanics',
                    'Clothing Technology',
                    'Construction Technology',
                    'Media Technology',
                    'Electronics Technology',
                    'Manufacturing Technology',
                    'Mechatronic',
                    'Garment Making and Interior Design',
                    'Leather Work',
                    'Culinary Arts',
                    'Hair Dressing and Beauty Therapy',
                    'Plumbing and Ceramics',
                    'Welding and Fabrication',
                    'Tourism and Travel',
                    'Air Conditioning and Refrigeration',
                    'Animal Keeping',
                    'Exterior Design and Landscaping',
                    'Building Construction',
                    'Photography',
                    'Graphic Designing and Animation',
                    'Food and Beverage',
                    'Motor Vehicle Mechanics',
                    'Carpentry and Joinery',
                    'Fire Fighting',
                    'Metalwork',
                    'Electricity',
                    'Land Surveying',
                    'Science Laboratory Technology',
                    'Printing Technology',
                    'Crop Production',
                ],
            ],

            // ✅ Montessori Curriculum
            'Montessori' => [
                'Nursery' => [
                    'Practical Life',
                    'Sensorial Development',
                    'Language',
                    'Mathematics',
                    'Science',
                    'Culture (Geography & History)',
                    'Arts',
                    'Basic Swahili',
                    'Basic French',
                    'Computer lessons',
                    'Music, Movement & Drama',
                    'Swimming',
                ],
            ],

            // ✅ IGCSE
            'IGCSE' => [
                'Primary' => [
                    'Mathematics',
                    'English',
                    'Science',
                    'Social Studies',
                    'Geography',
                    'History',
                    'Art',
                    'Music',
                    'PE',
                    'Kiswahili',
                    'French',
                    'ICT',
                    'PSHE',
                ],
                'Secondary' => [
                    'Mathematics',
                    'English Language',
                    'English Literature',
                    'Biology',
                    'Chemistry',
                    'Physics',
                    'History',
                    'Geography',
                    'Sociology',
                    'Global Perspectives',
                    'Economics',
                    'French',
                    'Spanish',
                    'Chinese',
                    'Kiswahili',
                    'Art and Design',
                    'Business Studies',
                    'Drama',
                    'Music',
                    'Computer Science',
                    'ICT',
                    'Design and Technology',
                    'Physical Education',
                ],
            ],

            // ✅ British
            'British' => [
                'Primary' => [
                    'Mathematics',
                    'English',
                    'Science',
                    'Social Studies',
                    'Geography',
                    'History',
                    'Art',
                    'Music',
                    'PE',
                    'Kiswahili',
                    'French',
                    'ICT',
                    'PSHE',
                ],
                'Secondary' => [
                    'Mathematics',
                    'English Language',
                    'English Literature',
                    'Biology',
                    'Chemistry',
                    'Physics',
                    'History',
                    'Geography',
                    'Sociology',
                    'Global Perspectives',
                    'Economics',
                    'French',
                    'Spanish',
                    'Chinese',
                    'Kiswahili',
                    'Art and Design',
                    'Business Studies',
                    'Drama',
                    'Music',
                    'Computer Science',
                    'ICT',
                    'Design and Technology',
                    'Physical Education',
                ],
            ],

            // ✅ International Baccalaureate (IB) – no levels
            'IB' => [
                'Primary' => [
                    'Theory of Knowledge',
                    'English Literature',
                    'English Language and Literature',
                    'French',
                    'Swahili',
                    'Spanish',
                    'Environmental Systems',
                    'History',
                    'Geography',
                    'Business Management',
                    'Economics',
                    'ITGS',
                    'Chemistry',
                    'Biology',
                    'Physics',
                    'Environmental Systems & Societies',
                    'Math Higher Level',
                    'Math Standard Level',
                    'Mathematical studies',
                    'Visual Arts',
                    'Theatre Art',
                ],
                'Secondary' => [
                    'Theory of Knowledge',
                    'English Literature',
                    'English Language and Literature',
                    'French',
                    'Swahili',
                    'Spanish',
                    'Environmental Systems',
                    'History',
                    'Geography',
                    'Business Management',
                    'Economics',
                    'ITGS',
                    'Chemistry',
                    'Biology',
                    'Physics',
                    'Environmental Systems & Societies',
                    'Math Higher Level',
                    'Math Standard Level',
                    'Mathematical studies',
                    'Visual Arts',
                    'Theatre Art',
                ],
            ],
        ];

        foreach ($data as $curriculumName => $levels) {
            $curriculum = Curriculum::firstOrCreate(['name' => $curriculumName]);

            foreach ($levels as $levelName => $courses) {
                // If curriculum has no levels, we use "General" as a placeholder
                $level = SchoolLevel::firstOrCreate([
                    'name' => $levelName,
                ]);

                foreach ($courses as $courseName) {
                    Course::firstOrCreate([
                        'name' => $courseName,
                        'curriculum_id' => $curriculum->id,
                        'school_level_id' => $level->id,
                    ]);
                }
            }
        }
    }
}
