<?php

namespace Database\Seeders;

use App\Models\School;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class SchoolSeeder extends Seeder
{
    public function run(): void
    {
        $schools = [
            [
                'name' => 'Westlands Academy',
                'slug' => Str::slug('Westlands Academy'),
                'description' => 'A private primary school in the heart of Westlands.',
                'year_of_establishment' => 2005,
                'religion_id' => 1,
                'school_level_id' => 2, // Primary
                'school_type_id' => 1, // Day
                'curriculum_id' => 1, // CBC
                'ownership' => 'Private',
                'gender_admission' => 'Mixed',
                'county_id' => 1,
                'country_id' => 1,
                'constituency_id' => 1,
                'ward_id' => 1,
                'school_uniform_id' => 1,
                'school_contact_id' => 1,
                'school_address_id' => 1,
                'school_operation_hour_id' => 1,
                'extended_school_service_id' => 3,
                'logo' => null,
                'website_url' => 'https://westlandsacademy.ke',
                'is_active' => true,
            ],
            [
                'name' => 'Langata Girls High School',
                'slug' => Str::slug('Langata Girls High School'),
                'description' => 'A public secondary school for girls in Langata.',
                'year_of_establishment' => 1992,
                'religion_id' => 1,
                'school_level_id' => 3,
                'school_type_id' => 2,
                'curriculum_id' => 6,
                'ownership' => 'Public',
                'gender_admission' => 'Female',
                'county_id' => 1,
                'country_id' => 1,
                'constituency_id' => 2,
                'ward_id' => 3,
                'school_uniform_id' => 2,
                'school_contact_id' => 2,
                'school_address_id' => 2,
                'school_operation_hour_id' => 2,
                'extended_school_service_id' => 1,
                'logo' => null,
                'website_url' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Kapsoya Primary School',
                'slug' => Str::slug('Kapsoya Primary School'),
                'description' => 'A public CBC primary school located in Eldoret.',
                'year_of_establishment' => 1980,
                'religion_id' => 1,
                'school_level_id' => 2,
                'school_type_id' => 1,
                'curriculum_id' => 1,
                'ownership' => 'Public',
                'gender_admission' => 'Mixed',
                'county_id' => 2,
                'country_id' => 1,
                'constituency_id' => 3,
                'ward_id' => 5,
                'school_uniform_id' => 3,
                'school_contact_id' => 3,
                'school_address_id' => 3,
                'school_operation_hour_id' => 3,
                'extended_school_service_id' => 2,
                'logo' => null,
                'website_url' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Frere Town College',
                'slug' => Str::slug('Frere Town College'),
                'description' => 'A private TVET college located in Mombasa.',
                'year_of_establishment' => 2010,
                'religion_id' => 2,
                'school_level_id' => 4,
                'school_type_id' => 3,
                'curriculum_id' => 5,
                'ownership' => 'Private',
                'gender_admission' => 'Mixed',
                'county_id' => 8,
                'country_id' => 1,
                'constituency_id' => 11,
                'ward_id' => 14,
                'school_uniform_id' => 4,
                'school_contact_id' => 4,
                'school_address_id' => 4,
                'school_operation_hour_id' => 4,
                'extended_school_service_id' => 1,
                'logo' => null,
                'website_url' => 'https://freretowncollege.ac.ke',
                'is_active' => true,
            ],
            [
                'name' => 'Zombe Mixed Secondary',
                'slug' => Str::slug('Zombe Mixed Secondary'),
                'description' => 'A mixed public secondary school in Kitui.',
                'year_of_establishment' => 1999,
                'religion_id' => 1,
                'school_level_id' => 3,
                'school_type_id' => 1,
                'curriculum_id' => 5,
                'ownership' => 'Public',
                'gender_admission' => 'Mixed',
                'county_id' => 18,
                'country_id' => 1,
                'constituency_id' => 21,
                'ward_id' => 24,
                'school_uniform_id' => 5,
                'school_contact_id' => 5,
                'school_address_id' => 5,
                'school_operation_hour_id' => 5,
                'extended_school_service_id' => 3,
                'logo' => null,
                'website_url' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Kapsabet Nursery School',
                'slug' => Str::slug('Kapsabet Nursery School'),
                'description' => 'A private nursery school following Montessori method.',
                'year_of_establishment' => 2015,
                'religion_id' => 1,
                'school_level_id' => 1,
                'school_type_id' => 1,
                'curriculum_id' => 4,
                'ownership' => 'Private',
                'gender_admission' => 'Mixed',
                'county_id' => 19,
                'country_id' => 1,
                'constituency_id' => 22,
                'ward_id' => 25,
                'school_uniform_id' => 5,
                'school_contact_id' => 5,
                'school_address_id' => 5,
                'school_operation_hour_id' => 5,
                'extended_school_service_id' => 3,
                'logo' => null,
                'website_url' => null,
                'is_active' => true,
            ],
        ];

        foreach ($schools as $school) {
            School::create($school);
        }
    }
}
